name: Build MasterX Mac

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Crear aplicacion Mac
      run: |
        pyinstaller --windowed --name MasterX window_tool_masterx_beta4_8_1_auto_download_prompt.py

    - name: Guardar resultado
      uses: actions/upload-artifact@v4
      with:
        name: MasterX-Mac
        path: dist/
